### ISSUE TITLE
Some physical thing reports fail to load properly

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#1105]
```
knockout-latest.js:20 Uncaught TypeError: Cannot read properties of undefined (reading 'resourceId')
    at eval (physical-thing.js:572:209)
    at Array.map (<anonymous>)
    at new viewModel (physical-thing.js:564:43)
    at Object.eval [as createViewModel] (knockout-latest.js:92:380)
    at c (knockout-latest.js:98:333)
    at a.gc.eval [as kc] (knockout-latest.js:99:294)
    at a.R.notifySubscribers (knockout-latest.js:42:453)
    at eval (knockout-latest.js:90:232)
    at b (knockout-latest.js:38:98)
    at MutationObserver.c (knockout-latest.js:38:136)
```

**Comment by chiatt** [comment]
Fixed in #1106
