### ISSUE TITLE
Bulk Data Manager, Import Branch Excel, upload hands on validation step (AfS dev/1.0.x, Arches stable/7.4.0)

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches-for-science-prj#1229]
I'm using AfS to better understand and document the Bulk Data Manager (see arches-docs: https://github.com/archesproject/arches-docs/blob/95a5b12367353a1030fc4ebf8fa7ca36b9509242/docs/administering/bulk-data-manager.txt#L42). 

In testing an upload of an Excel workbook with 1 record created for the AfS Dimension branch I ran into a problem. The validation step never completes. The frontend makes repeatly makes requests to the AfS backend as so:

`afs7             | [21/Jul/2023 00:05:53] "GET /etl-manager?action=loadEvent&page=1 HTTP/1.1" 200 4242`

Those requests repeat endlessly (even after 20 minutes or so, for a 2 line Excel import). It seems the backend never finishes the validation step. 

I'm attaching a copy of my Excel workbook with some data that I was hoping to import. 
[Dimension.xlsx](https://github.com/archesproject/arches-for-science-prj/files/12114868/Dimension.xlsx)

**Comment by ekansa** [comment]
From the "Task Status" tab, I tried to stop the import (hung on validation) process. Here's what got logged:

```
afs7             | [21/Jul/2023 00:55:37] "GET /etl-manager?action=loadEvent&page=1 HTTP/1.1" 200 4242
afs7             | Internal Server Error: /etl-manager
afs7             | Traceback (most recent call last):
afs7             |   File "/root/.local/lib/python3.10/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors
afs7             |     yield
afs7             |   File "/root/.local/lib/python3.10/site-packages/kombu/connection.py", line 459, in _ensure_connection
afs7             |     return retry_over_time(
afs7             |   File "/root/.local/lib/python3.10/site-packages/kombu/utils/functional.py", line 318, in retry_over_time
afs7             |     return fun(*args, **kwargs)
afs7             |   File "/root/.local/lib/python3.10/site-packages/kombu/connection.py", line 941, in _connection_factory
afs7             |     self._connection = self._establish_connection()
afs7             |   File "/root/.local/lib/python3.10/site-packages/kombu/connection.py", line 867, in _establish_connection
afs7             |     conn = self.transport.establish_connection()
afs7             |   File "/root/.local/lib/python3.10/site-packages/kombu/transport/pyamqp.py", line 203, in establish_connection
afs7             |     conn.connect()
afs7             |   File "/root/.local/lib/python3.10/site-packages/amqp/connection.py", line 323, in connect
afs7             |     self.transport.connect()
afs7             |   File "/root/.local/lib/python3.10/site-packages/amqp/transport.py", line 129, in connect
afs7             |     self._connect(self.host, self.port, self.connect_timeout)
afs7             |   File "/root/.local/lib/python3.10/site-packages/amqp/transport.py", line 184, in _connect
afs7             |     self.sock.connect(sa)
afs7             | ConnectionRefusedError: [Errno 111] Connection refused
afs7             |
afs7             | The above exception was the direct cause of the following exception:
afs7             |
afs7             | Traceback (most recent call last):
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
afs7             |     response = get_response(request)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
afs7             |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
afs7             |     return self.dispatch(request, *args, **kwargs)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
afs7             |     return bound_method(*args, **kwargs)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
afs7             |     return view_func(request, *args, **kwargs)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
afs7             |     return handler(request, *args, **kwargs)
afs7             |   File "/web_root/arches/arches/app/views/etl_manager.py", line 166, in get
afs7             |     response = self.stop_loading(loadid)
afs7             |   File "/web_root/arches/arches/app/views/etl_manager.py", line 109, in stop_loading
afs7             |     remote_control.revoke(task_id=taskid, terminate=True)
afs7             |   File "/root/.local/lib/python3.10/site-packages/celery/app/control.py", line 496, in revoke
afs7             |     return self.broadcast('revoke', destination=destination, arguments={
afs7             |   File "/root/.local/lib/python3.10/site-packages/celery/app/control.py", line 741, in broadcast
afs7             |     return self.mailbox(conn)._broadcast(
afs7             |   File "/root/.local/lib/python3.10/site-packages/kombu/pidbox.py", line 330, in _broadcast
afs7             |     chan = channel or self.connection.default_channel
afs7             |   File "/root/.local/lib/python3.10/site-packages/kombu/connection.py", line 960, in default_channel
afs7             |     self._ensure_connection(**conn_opts)
afs7             |   File "/root/.local/lib/python3.10/site-packages/kombu/connection.py", line 458, in _ensure_connection
afs7             |     with ctx():
afs7             |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
afs7             |     self.gen.throw(typ, value, traceback)
afs7             |   File "/root/.local/lib/python3.10/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
afs7             |     raise ConnectionError(str(exc)) from exc
afs7             | kombu.exceptions.OperationalError: [Errno 111] Connection refused
afs7             | [21/Jul/2023 00:55:40] "GET /etl-manager?action=stop&loadid=852e888a-1237-4d7b-a481-30ad06a9aeaf HTTP/1.1" 500 200022
afs7             | [21/Jul/2023 00:55:42] "GET /etl-manager?action=loadEvent&page=1 HTTP/1.1" 200 4242
```

**Comment by chiatt** [comment]
I'm not sure if this is the issue, but looks like 'Dimension' is a branch rather than a resource model. I appears the template dropdown shows both resource models and branches. 
<img width="1059" alt="image" src="https://github.com/archesproject/arches-for-science-prj/assets/1877663/0fc68482-36bb-4d5a-b77d-e1003dd8cff9">

**Comment by chiatt** [comment]
It's a quick fix. I'll take care of it as part of this ticket.

**Comment by chiatt** [comment]
Moving to core as fix must be done in there
