### ISSUE TITLE
Phys thing search raises elastic error (but silently transformed to 200 OK)

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1291]
In the new project workflow add physical thing step, type into the search bar.

```py
disco             | 2023-09-11 20:08:51,889 arches.app.search.search ERROR    2023-09-11 20:08:51.889311: WARNING: search failed for query: {'bool': {'should': [{'match_phrase_prefix': {'value': {'query': 'ere'}}}, {'match_phrase_prefix': {'value.folded': {'query': 'ere'}}}, {'match': {'value.folded': {'query': 'ere', 'fuzziness': 'AUTO', 'prefix_length': 3}}}], 'must': [{'match_phrase_prefix': {'language': {'query': 'en'}}}], 'must_not': [], 'filter': [], 'minimum_should_match': 1}} 
disco             | Exception detail: BadRequestError(400, 'search_phase_execution_exception', 'failed to create query: Can only use phrase prefix queries on text fields - not on [language] which is of type [keyword]')
disco             | Traceback (most recent call last):
disco             |   File "/usr/local/lib/python3.10/dist-packages/arches/app/search/search.py", line 151, in search
disco             |     ret = self.es.search(**kwargs).body
disco             |   File "/usr/local/lib/python3.10/dist-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
disco             |     return api(*args, **kwargs)
disco             |   File "/usr/local/lib/python3.10/dist-packages/elasticsearch/_sync/client/__init__.py", line 3863, in search
disco             |     return self.perform_request(  # type: ignore[return-value]
disco             |   File "/usr/local/lib/python3.10/dist-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
disco             |     raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
disco             | elasticsearch.BadRequestError: BadRequestError(400, 'search_phase_execution_exception', 'failed to create query: Can only use phrase prefix queries on text fields - not on [language] which is of type [keyword]')
disco             | [11/Sep/2023 20:08:51] "GET /search/terms?start=0&page_limit=7&q=ERE&_=1694462907654 HTTP/1.1" 200 29
```

Interestingly, the 400 from elastic is transformed to 200 OK.

**Comment by jacobtylerwalls** [comment]
Fixed in #1325
