### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'project')

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1306]
1. Analysis Area Workflow
2. Annotation step: Draw a polygon
3. Save the polygon
4. Previous step
5. Next step (you're now at annotation step again)
6. Select the polygon from step 2
7. Drag a midline drag handle (not the vertex)

```js
leaflet.draw.js:8 Uncaught TypeError: Cannot read properties of null (reading 'project')
    at i._getMiddleLatLng (leaflet.draw.js:8:31285)
    at i._createMiddleMarker (leaflet.draw.js:8:30386)
    at i.a (leaflet.draw.js:8:30935)
    at i.fire (leaflet.js:5:4951)
    at i._onDragEnd (leaflet.js:5:71668)
    at i.fire (leaflet.js:5:4951)
    at i.finishDrag (leaflet.js:5:60364)
    at i._onUp (leaflet.js:5:60054)
    at HTMLDocument.s (leaflet.js:5:22654)
```

**Comment by jacobtylerwalls** [comment]
Never mind, this is just https://github.com/Leaflet/Leaflet.draw/issues/876
