### ISSUE TITLE
X/Y data: deleting all files from upload step allows advancing to next step 

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1363]
XY loader:
1. Data Files and Location step > Add a file
2. Remove the file
3. Next

Expected: next button disabled
Actual:
```js
select-renderer-step.js:135 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '@tile_id')
    at eval (select-renderer-step.js:135:29)
    at Array.map (<anonymous>)
    at _callee4$ (select-renderer-step.js:132:16)
    at tryCatch (select-renderer-step.js:2:1062)
    at Generator.eval (select-renderer-step.js:2:3012)
    at Generator.eval [as next] (select-renderer-step.js:2:1699)
    at asyncGeneratorStep (select-renderer-step.js:3:103)
    at _next (select-renderer-step.js:4:194)
```

**Comment by jacobtylerwalls** [comment]
Fixed in #1388
