### ISSUE TITLE
XY uploader: KeyError: 'clientFileId'

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1370]
Uploading a file (probably because I'm not using a realistic file) fails with:
```py
Traceback (most recent call last):
  File "/web_root/arches-for-science/arches_for_science/views/workflows/upload_dataset/select_dataset_files_step.py", line 174, in post
    file_response = [
  File "/web_root/arches-for-science/arches_for_science/views/workflows/upload_dataset/select_dataset_files_step.py", line 175, in <listcomp>
    {"name": f[0]["name"],"path":f[0]["path"],"clientId":f[0]["clientFileId"], "renderer": f[0]["renderer"], "format": f[0].get("format", None), "tileId": f[0]["tileid"]}
KeyError: 'clientFileId'
```

An appropriate error is shown in the UI: "Failed to upload files. Try again or contact an administrator."

But then refreshing the page hangs with this failure:
```py
Internal Server Error: /resource/related/c59aca3a-6e51-4a43-b811-93f134985022
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/web_root/arches/arches/app/utils/decorators.py", line 100, in wrapper
    return function(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/web_root/arches/arches/app/views/resource.py", line 875, in get
    resource = Resource.objects.get(pk=resourceid)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
arches.app.models.resource.Resource.DoesNotExist: Resource matching query does not exist.
[19/Oct/2023 12:12:45] "GET /resource/related/c59aca3a-6e51-4a43-b811-93f134985022 HTTP/1.1" 500 128157
```

Initiated from here:
```js
return window.fetch("".concat(arches.urls.related_resources).concat(part.datasetId()));
```

**Comment by jacobtylerwalls** [comment]
Duplicate of #1342
