### ISSUE TITLE
[observation info] Cannot write value to a ko.computed unless you specify `write`

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1428]
X/Y Workflow, observation info:
- Select an instrument
- Undo

```js
Uncaught (in promise) Error: Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.
    at WorkflowComponentAbstract.e [as hasUnsavedData] (knockout-latest.js:54:426)
    at params.form.reset (instrument-info-step.js:176:19)
    at WorkflowComponentAbstract._resetComponent (workflow-component-abstract.js:677:38)
    at eval (workflow-step.js:161:39)
    at new Promise (<anonymous>)
    at eval (workflow-step.js:160:30)
    at Array.forEach (<anonymous>)
    at eval (workflow-step.js:159:63)
    at new Promise (<anonymous>)
    at WorkflowStep.undo (workflow-step.js:157:14)
```

**Comment by aarongundel** [comment]
@jacobtylerwalls I cannot replicate this issue; it's not happening for me.  I assume by undo you mean click the close button on the right of the drop.  I don't see any errors when I do that.

**Comment by jacobtylerwalls** [comment]
Ah,I was referring to the orange undo button at the bottom (between previous and next steps).
