### ISSUE TITLE
ManifestXDigitalResource DoesNotExist error when adding manifest

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1466]
1. Load afs-test-pkg
2. Sample Taking Workflow > Select manifest > Sample Info step

```py
Traceback (most recent call last):
  File "/web_root/arches-for-science/arches_for_science/views/manifest_x_canvas.py", line 17, in get
    digital_resource = ManifestXDigitalResource.objects.get(manifest=manifest).digitalresource
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /manifest_x_canvas/
Exception Value: ManifestXDigitalResource matching query does not exist.
```

I assume we need to add these records to the preliminary SQL for afs-test-pkg?

**Comment by chiatt** [comment]
Bummer - I would have expected the receiver to create them.

**Comment by chiatt** [comment]
I think the problem is that we are not managing this manifest, so we don't want to try to manage digital resource instances for those canvases. We have to treat remote vs local (cantaloupe) manifest canvas differently. Maybe we just need to handle for this error.
