### ISSUE TITLE
Advancing to final step of sample taking without taking one raises TypeError

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1480]
1. Sample Taking > add a sample > finish workflow
2. Sample Taking > select the same parent physical object
3. Advance past sample taking step without creating a sample

My guess is that you should not be able to advance to the final step without new samples.

```js
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at viewModel.eval (sample-taking-final-step.js:123:71)
    at Function.notifySubscribers (knockout-latest.js:42:453)
    at Function.wa (knockout-latest.js:47:255)
    at c (knockout-latest.js:46:494)
    at eval (summary-step.js:10:16)
```

**Comment by chiatt** [comment]
Yeah - that's right. The user needs to create a sample in order to proceed.
