### ISSUE TITLE
Report workflow allows advancing to final step without selecting a file

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-for-science-prj#1507]
Report workflow > Select Files step > select no files > Next

```js
Uncaught TypeError: Cannot read properties of undefined (reading 'files')
    at Workflow.getDataFromComponentPath (workflow.js:201:24)
    at eval (workflow-component-abstract.js:558:70)
    at Array.forEach (<anonymous>)
    at WorkflowComponentAbstract.loadComponent (workflow-component-abstract.js:555:52)
    at a.gc.eval [as kc] (workflow-component-abstract.js:510:14)
    at Function.notifySubscribers (knockout-latest.js:42:453)
    at Function.yd (knockout-latest.js:59:231)
    at Function.ha (knockout-latest.js:58:406)
    at Function.Gc (knockout-latest.js:58:251)
    at Function.notifySubscribers (knockout-latest.js:42:453)
```

**Comment by jacobtylerwalls** [comment]
Similar to #1363

**Comment by chiatt** [comment]
A report doesn't necessarily need any selected files, so it seems like we just need to handle for this error.
